import typer
import os
import sys

from rich.console import Console

project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_dir not in sys.path:
    sys.path.append(project_dir)

from model.command_generation_request import CommandGenerationRequest
from core.command_generator import CommandGenerator

console = Console(width=100)
llp = typer.Typer()

@llp.command()
def generate_shell_command(prompt: str):
    with console.status('Generating command'):

        request = CommandGenerationRequest(
            user_prompt=prompt
        )

        generated_command = CommandGenerator().generate_bash_command(
            request=request
        )

        console.print()

        console.print(
            generated_command.command, 
            style='green', 
            justify='center', 
            end='\n\n'
        )

        console.print(
            generated_command.explanation,
            end='\n\n'
        )

        console.print(
            'Warning: Commands generated by LLPrompt can cause irreversible damage to your computer. Please inspect the command thoroughly before running it.', 
            style='red bold'
        )

if __name__ == "__main__":
    llp()